# Generated by Django 3.1 on 2021-04-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortFolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='Awards',
            new_name='awards',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='git',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
